spring:
  main:
    banner-mode: "off"

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when_authorized

server:
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

